### PR TITLE
The geopackage.org samples section was replaced

### PR DESCRIPTION
**Pull request by jyutzler**

### CODE REVIEW

**Comment by danielbarela** [comment]
Shouldn't the link be changed to: http://www.geopackage.org/data.html ?

**Comment by jyutzler** [comment]
`http://www.geopackage.org/data.html` is more for real data than for sample data.

**Comment by danielbarela** [comment]
The intent of that link is to find GeoPackages, so I think the wording should be changed to indicate that more GeoPackages are available at the link to the data page (http://www.geopackage.org/data.html).

**Comment by jyutzler** [comment]
OK, that's fine.

**Comment by danielbarela** [comment]
OBE

**Pull request closed without merging**
